/**
 * OBJ Export for Waveguide Meshes
 * ================================
 *
 * Exports mesh data to Wavefront OBJ format for 3D applications.
 */

import type { MeshData } from '../types/waveguide'

/**
 * Export mesh to Wavefront OBJ format.
 *
 * Creates a quad mesh with:
 * - Vertex list (v x y z)
 * - Face list (f v1 v2 v3 v4)
 *
 * Coordinate system:
 * - x: horizontal (cross-section)
 * - y: vertical (cross-section)
 * - z: axial (along horn)
 *
 * @param meshData - Generated mesh data
 * @returns OBJ format string
 */
export function exportToOBJ(meshData: MeshData | null): string {
  if (!meshData) return ''

  const { rings, numSlices } = meshData
  let obj = '# R-OSSE Waveguide Mesh\n'
  obj += '# Generated by Horn Designer\n'
  obj += '# https://github.com/taryune/horn-designer\n\n'

  // Write vertices
  for (const { ring } of rings) {
    for (const [px, py, pz] of ring) {
      obj += `v ${px.toFixed(4)} ${py.toFixed(4)} ${pz.toFixed(4)}\n`
    }
  }

  obj += '\n'

  // Write faces (quads connecting adjacent rings)
  const vertsPerRing = numSlices + 1
  for (let ri = 0; ri < rings.length - 1; ri++) {
    for (let si = 0; si < numSlices; si++) {
      // OBJ uses 1-based indexing
      const a = ri * vertsPerRing + si + 1
      const b = ri * vertsPerRing + si + 2
      const c = (ri + 1) * vertsPerRing + si + 2
      const d = (ri + 1) * vertsPerRing + si + 1
      obj += `f ${a} ${b} ${c} ${d}\n`
    }
  }

  return obj
}

/**
 * Download OBJ file to user's computer.
 *
 * @param meshData - Generated mesh data
 * @param filename - Output filename (default: "waveguide.obj")
 */
export function downloadOBJ(meshData: MeshData | null, filename: string = 'waveguide.obj'): void {
  const obj = exportToOBJ(meshData)
  if (!obj) return

  const blob = new Blob([obj], { type: 'text/plain;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)

  link.setAttribute('href', url)
  link.setAttribute('download', filename)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
